//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MachineTest.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransID { get; set; }
        public int ItemID { get; set; }
        public string TransType { get; set; }
        public int TransQty { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
    }
}
